import { type NextPage } from "next";
import Head from "next/head";
import { useUser, SignInButton } from "@clerk/nextjs";

import { type RouterOutputs, api } from "~/utils/api";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";

dayjs.extend(relativeTime);

const Home: NextPage = () => {
  const user = useUser();

  console.log(user);

  const CreatePostWizard = () => {
    const { user } = useUser();
    if (!user) return null;

    return (
      <div className="flex w-full gap-4">
        <Image
          src={user.profileImageUrl}
          alt="profile image"
          className="h-14 w-14 rounded-full"
          width={56}
          height={56}
        />
        <input
          type="text"
          placeholder="Type some emojis"
          className="p grow bg-transparent outline-none"
        />
      </div>
    );
  };

  // we want an element from this array type,
  type postWithUser = RouterOutputs["postsRouter"]["getAll"][number];
  const PostView = (props: postWithUser) => {
    const { post, author } = props;
    return (
      <div key={post.id} className="flex gap-3 border-b border-slate-400 p-4">
        <Image
          src={author.profileImageUrl}
          alt={`${author.username}'s profile image}`}
          className="h-14 w-14 rounded-full"
          width={56}
          height={56}
        />
        <div className="flex flex-col">
          <div className="flex gap-1  text-slate-300">
            {`@${author.username}`}
            <span>·</span>
            <span>{dayjs(post.createdAt).fromNow()}</span>
          </div>
          <span>{post.content}</span>
        </div>
      </div>
    );
  };

  const { data, isLoading } = api.postsRouter.getAll.useQuery();

  if (isLoading) return <div>loading....</div>;
  if (!data) return <div>Something is wrong...</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-500 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {[...data, ...data]?.map((fullpost) => (
              <PostView {...fullpost} key={fullpost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
