import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useUser, SignOutButton, SignInButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();

  const CreatePostWizard = () => {
    const { user } = useUser();
    if (!user) return null;

    return (
      <div className="flex w-full gap-4">
        <img
          src={user.profileImageUrl}
          alt="profile image"
          className="h-16 w-16 rounded-full"
        />
        <input
          type="text"
          placeholder="Type some emojis"
          className="p grow bg-transparent outline-none"
        />
      </div>
    );
  };

  const { data, isLoading } = api.postsRouter.getAll.useQuery();

  if (isLoading) return <div>loading....</div>;
  if (!data) return <div>Something is wrong...</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-500 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {[...data, ...data].map((posts) => (
              <div key={posts.id} className="border-b border-slate-400 p-8">
                {posts.content}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
